DROP INDEX CONTABIL02.IDX_RPS_COMPUESTO;

CREATE INDEX CONTABIL02.IDX_RPS_COMPUESTO ON CONTABIL02.REPORT_PROCESS_SALDOS
(PERIODO_FINAL, CODIGO_CUENTA, CODIGO_INTERNO_CUENTA, CODIGO_MEMPRESA)
LOGGING
TABLESPACE CONTABILIDAD
REVERSE;
