


CREATE TABLE CONTABIL02.SAP_DET_CARGA_ARCH_COMPARATIVO
(
  CODIGO_CARGA                   NUMBER(10),
  CODIGO_CARGA_DET               NUMBER(10),
  CODIGO_DANE                    VARCHAR2(30 BYTE),
  CODIGO_CUENTA_CONTABLE         VARCHAR2(20 BYTE),
  SALDO_FINAL_PERIODO            NUMBER,
  INSTITUCION_EDUCATIVA_NOMBRE   VARCHAR2(60 BYTE),      
  USUARIO_EMPRESA                VARCHAR2(30 BYTE) DEFAULT USER,
  CODIGO_MEMPRESA                VARCHAR2(50 BYTE) DEFAULT SYS_CONTEXT('CTX_SICOF','CODIGO_MEMPRESA'),
  FECHA_REGISTRO                 DATE           DEFAULT SYSDATE  
)
;
/



CREATE SEQUENCE CONTABIL02.SEQ_SAP_DET_CARGA_ARCH_COMPARA
  START WITH 1001
  MAXVALUE 9999999999999
  MINVALUE 1
  CYCLE
  NOCACHE
  NOORDER
;
/



CREATE OR REPLACE PUBLIC SYNONYM SEQ_SAP_DET_CARGA_ARCH_COMPARA FOR CONTABIL02.SEQ_SAP_DET_CARGA_ARCH_COMPARA
;
/



CREATE OR REPLACE TRIGGER CONTABIL02.TGR_BI_SAP_DET_CARGA_ARCH_COMP 
BEFORE INSERT ON CONTABIL02.SAP_DET_CARGA_ARCH_COMPARATIVO 
FOR EACH ROW
BEGIN
    IF :new.CODIGO_CARGA_DET IS NULL OR :new.CODIGO_CARGA_DET = 0 THEN
        SELECT SEQ_SAP_DET_CARGA_ARCH_COMPARA.NEXTVAL
        INTO :new.CODIGO_CARGA_DET
        FROM  dual ;
    END IF;

END
;
/



CREATE INDEX CONTABIL02.IDX_SAP_DET_CARG_ARC_COD_CARGA
ON CONTABIL02.SAP_DET_CARGA_ARCH_COMPARATIVO
(CODIGO_CARGA)
;
/




CREATE UNIQUE INDEX CONTABIL02.IDX_SAP_DET_CARGA_ARCH_COMPARA 
ON CONTABIL02.SAP_DET_CARGA_ARCH_COMPARATIVO
(CODIGO_CARGA_DET)
;
/



ALTER TABLE CONTABIL02.SAP_DET_CARGA_ARCH_COMPARATIVO ADD (
  CONSTRAINT PK_SAP_DET_CARGA_ARCH_COMPARAT
  PRIMARY KEY
  (CODIGO_CARGA_DET)
  USING INDEX CONTABIL02.IDX_SAP_DET_CARGA_ARCH_COMPARA
  ENABLE VALIDATE)
;
/



CREATE OR REPLACE FORCE VIEW CONTABIL01.SAP_DET_CARGA_ARCH_COMPARATIVO
(
   CODIGO_CARGA,
   CODIGO_CARGA_DET,
   CODIGO_DANE,
   CODIGO_CUENTA_CONTABLE,
   SALDO_FINAL_PERIODO,
   INSTITUCION_EDUCATIVA_NOMBRE,
   USUARIO_EMPRESA,
   CODIGO_MEMPRESA,
   FECHA_REGISTRO
)
AS
   SELECT CODIGO_CARGA,
          CODIGO_CARGA_DET,
          CODIGO_DANE,
          CODIGO_CUENTA_CONTABLE,
          SALDO_FINAL_PERIODO,
          INSTITUCION_EDUCATIVA_NOMBRE,
          USUARIO_EMPRESA,
          CODIGO_MEMPRESA,
          FECHA_REGISTRO
     FROM CONTABIL02.SAP_DET_CARGA_ARCH_COMPARATIVO
    /*WHERE    codigo_mempresa IN
                (DECODE (SYS_CONTEXT ('CTX_SICOF', 'CODIGO_MEMPRESA'),
                         '9999999999', '-1',
                         SYS_CONTEXT ('CTX_SICOF', 'CODIGO_MEMPRESA')),
                 '9999999999')
          OR SYS_CONTEXT ('CTX_SICOF', 'CODIGO_MEMPRESA') = '0'*/
;
/



CREATE OR REPLACE PUBLIC SYNONYM SAP_DET_CARGA_ARCH_COMPARATIVO FOR CONTABIL01.SAP_DET_CARGA_ARCH_COMPARATIVO
;
/



