

CREATE OR REPLACE FORCE VIEW CONTABIL01.V_SALDOS_CUENTAS_CONTABLE_TODO
(
   CODIGO_INTERNO_CUENTA,
   CODIGO_TERCERO,
   CCOSTOS,
   PERIODO,
   SALDO_INICIAL,
   SALDO_FINAL,
   VALOR_DEBITO,
   VALOR_CREDITO,
   USUARIO_EMPRESA,
   CODIGO_MEMPRESA,
   FECHA_REGISTRO
)
AS
   SELECT CODIGO_INTERNO_CUENTA,
          CODIGO_TERCERO,
          CCOSTOS,
          PERIODO,
          SALDO_INICIAL,
          SALDO_FINAL,
          VALOR_DEBITO,
          VALOR_CREDITO,
          USUARIO_EMPRESA,
          CODIGO_MEMPRESA,
          FECHA_REGISTRO
     FROM CONTABIL02.SALDOS_CUENTAS_CONTABLES
;
/


CREATE OR REPLACE PUBLIC SYNONYM V_SALDOS_CUENTAS_CONTABLE_TODO FOR CONTABIL01.V_SALDOS_CUENTAS_CONTABLE_TODO
;
/
