

CREATE OR REPLACE FORCE VIEW CONTABIL01.V_MAE_VALIDACION_CIERRE_TODO
(
   CODIGO_VALIDACION,
   CODIGO_USUARIO_ELABORA,
   CODIGO_USUARIO_APRUEBA,
   ESTADO,
   PERIODO_INICIAL,
   PERIODO_FINAL,
   FECHA_ELABORACION,
   FECHA_APROBACION,
   CODIGO_EMPRESA,
   CODIGO_MEMPRESA,
   FECHA_REGISTRO
)
AS
   SELECT CODIGO_VALIDACION,
          CODIGO_USUARIO_ELABORA,
          CODIGO_USUARIO_APRUEBA,
          ESTADO,
          PERIODO_INICIAL,
          PERIODO_FINAL,
          FECHA_ELABORACION,
          FECHA_APROBACION,
          CODIGO_EMPRESA,
          CODIGO_MEMPRESA,
          FECHA_REGISTRO
     FROM CONTABIL02.MAE_VALIDACION_CIERRE
/*    WHERE    codigo_mempresa IN
                (DECODE (SYS_CONTEXT ('CTX_SICOF', 'CODIGO_MEMPRESA'),
                         '9999999999', '-1',
                         SYS_CONTEXT ('CTX_SICOF', 'CODIGO_MEMPRESA')),
                 '9999999999')
          OR SYS_CONTEXT ('CTX_SICOF', 'CODIGO_MEMPRESA') = '0'*/
;
/


CREATE OR REPLACE PUBLIC SYNONYM V_MAE_VALIDACION_CIERRE_TODO FOR CONTABIL01.V_MAE_VALIDACION_CIERRE_TODO
;
/
